"""Shared threshold constants for public-signal analysis and decay classification."""

DECAY_STICKY_THRESHOLD = 0.30
DECAY_NOVELTY_THRESHOLD = 0.70
HIGH_DECAY_ACTION_THRESHOLD = 0.80

POSITIVE_SIGNAL_NEGATIVE_RATIO_THRESHOLD = 0.20
NEGATIVE_SIGNAL_NEGATIVE_RATIO_THRESHOLD = 0.30

HIGH_ENGAGEMENT_MENTION_THRESHOLD = 20
LOW_AWARENESS_MENTION_THRESHOLD = 10
